---

- name: "Update last operation"
  asb_last_operation:
    description: "0%: Starting"
  when: in_cluster

- name: 'Verify if oc cli is installed'
  command: oc version
  register: oc_version

- debug:
    msg: "{{ oc_version }}"

- name: 'Remove Admin roles to users'
  command: "oc adm policy remove-role-from-user admin {{ item }} -n {{ project_name }}"
  with_items: "{{ admin_users.split(',') }}"

- name: 'Remove readonly roles to users'
  command: "oc adm policy remove-role-from-user view {{ item }} -n {{ project_name }}"
  with_items: "{{ readonly.split(',') }}"

- name: 'Remove Project'
  command: "oc delete project {{ project_name }}"

- name: "Update last operation"
  asb_last_operation:
    description: "100%: Done"
  when: in_cluster